Insert into Bebida values(2,'Sprite')
Insert into Bebida values(3,'Manzanita')
Insert into Bebida values(4,'FuzeTea')
Insert into Bebida values(5,'Fanta')
Insert into Bebida values(6,'Agua Mineral')
Insert into Bebida values(7,'Agua Natural')
Insert into Bebida values(8,'Cafe')
Insert into Bebida values(9,'Limonada')
Insert into Bebida values(10,'Naranjada')
Insert into Bebida values(11,'Piña colada')

Insert into Cliente values (2,'Ornelas','Castillo','Lizbeth Alexandra')
Insert into Cliente values (3,'Godinez','Perez','Fermin')
Insert into Cliente values (4,'Carreon','Uriel','Brandon')
Insert into Cliente values (5,'Carpio','Herrera','Jose Juan')
Insert into Cliente values (6,'Laureano','Martinez','Felipe ')
Insert into Cliente values (7,'Tovar','Hilario','Tomas')
Insert into Cliente values (8,'Yañez','Torres','Antonio')
Insert into Cliente values (9,'Guajardo','Hernandez','Bernardo')
Insert into Cliente values (10, 'Guajardo','Castillo','Olga Lydia')
Insert into Cliente values (11,'Ortiz','Castillo','Alexandra')
Insert into Cliente values (12,'Fernandez','Perez','Fernando')
Insert into Cliente values (13,'Carrizales','Uriel','Pedro')
Insert into Cliente values (14,'Renteria','Herrera','Jose Felipe')
Insert into Cliente values (15,'Gonzalez','Martinez','Felipe ')
Insert into Cliente values (16,'Gomez','Hilario','Ricardo')
Insert into Cliente values (17,'Hernandez','Torres','Eduardo')
Insert into Cliente values (18,'Tamez','Hernandez','Max')
Insert into Cliente values (19, 'Blanco','Castro','Marin')
Insert into Cliente values (20, 'Guzman','Rodriguez','Melisa')



Insert into Platillo values (1,'Caldo de res')
Insert into Platillo values (2,'Caldo de pollo')
Insert into Platillo values (3,'Caldo de pescado')
Insert into Platillo values (4,'Sopa de arroz')
Insert into Platillo values (5,'Albondigas')
Insert into Platillo values (6,'Tacos de carne asada')
Insert into Platillo values (7,'Tacos de trompo')
Insert into Platillo values (8,'Hamburguesa basica')
Insert into Platillo values (9,'Hamburguesa doble')
Insert into Platillo values (10,'Hamburguesa 4to libra')
Insert into Platillo values (11,'Hamburguesa sin queso')
Insert into Platillo values (12,'Hamburguesa con trompo')
Insert into Platillo values (13,'Hamburguesa F')
Insert into Platillo values (14,'Hamburguesa infantil')
Insert into Platillo values (15,'Hamburguesa Fornite')
Insert into Platillo values (16,'Hamburguesa K')
Insert into Platillo values (17,'Hamburguesa Triple')
Insert into Platillo values (18,'Torta basica')
Insert into Platillo values (19,'Torta de res')
Insert into Platillo values (20,'Torta de pollo')
Insert into Platillo values (21,'Torta ahogada')
Insert into Platillo values (22,'Torta de tamal')
Insert into Platillo values (23,'Filete de res 3/4')
Insert into Platillo values (24,'Filete de pescado')
Insert into Platillo values (25,'De la casa')
Insert into Platillo values (26,'Spagetti normal')
Insert into Platillo values (27,'Spagetti con albondigas')
Insert into Platillo values (28,'Mojarra')
Insert into Platillo values (29,'Boneless')
Insert into Platillo values (30,'Ramen')
Insert into Platillo values (31,'Maruchan de la casa')

Insert into Postre values (1,'Chessecake')
Insert into Postre values (2,'Helado choco')
Insert into Postre values (3,'Helado Vaini')
Insert into Postre values (4,'Sundae')
Insert into Postre values (5,'Pay de pinia')
Insert into Postre values (6,'Postre de limon')
Insert into Postre values (7,'Choco-roles ')
Insert into Postre values (8,'3 leches')
Insert into Postre values (9,'Creme Brule')
Insert into Postre values (10,'Pay de queso wine')
Insert into Postre values (11,'Galletas de coco')
Insert into Postre values (12,'Chokis')
Insert into Postre values (13,'Gomitas')



Insert into Info_Gral values (1,'EL LINGOTE',924839,'ellingote@gmail.com')

Insert into Reservacion values (1,1)
Insert into Reservacion values (2,2)
Insert into Reservacion values (3,3)
Insert into Reservacion values (4,4)
Insert into Reservacion values (5,5)
Insert into Reservacion values (6,6)
Insert into Reservacion values (7,7)


Insert into Ticket values (1,1,2,1,1)
Insert into Ticket values (2,1,5,1,1)
Insert into Ticket values (3,1,1,1,1)
Insert into Ticket values (4,1,3,1,1)
Insert into Ticket values (5,3,2,1,1)
Insert into Ticket values (6,1,2,1,1)
Insert into Ticket values (7,1,2,1,1)
Insert into Ticket values (8,1,3,1,1)
Insert into Ticket values (9,1,2,1,1)
Insert into Ticket values (10,1,7,1,1)
Insert into Ticket values (11,1,2,3,1)
Insert into Ticket values (12,1,4,1,1)
Insert into Ticket values (13,1,2,1,1)
Insert into Ticket values (14,1,2,3,1)
Insert into Ticket values (15,1,4,1,1)
Insert into Ticket values (16,3,2,1,1)
Insert into Ticket values (17,1,2,1,1)
Insert into Ticket values (18,1,6,1,1)
Insert into Ticket values (19,1,8,1,1)
Insert into Ticket values (20,1,2,5,1)
Insert into Ticket values (21,1,3,1,1)
Insert into Ticket values (22,5,2,3,1)
Insert into Ticket values (23,1,7,1,1)

Insert into Pedido values (1,1,3,3)
Insert into Pedido values (2,2,2,5)
Insert into Pedido values (3,5,2,6)
Insert into Pedido values (4,6,2,2)
Insert into Pedido values (5,3,2,1)
Insert into Pedido values (6,3,2,4)
Insert into Pedido values (7,7,2,5)
Insert into Pedido values (8,10,2,6)
Insert into Pedido values (9,1,2,4)
Insert into Pedido values (10,12,2,4)
Insert into Pedido values (11,6,2,3)
Insert into Pedido values (12,1,2,2)
Insert into Pedido values (13,1,2,5)
Insert into Pedido values (14,1,4,2)
Insert into Pedido values (15,1,2,5)
Insert into Pedido values (16,4,2,8)
Insert into Pedido values (17,9,2,9)
Insert into Pedido values (18,3,2,10)
Insert into Pedido values (19,1,2,3)
Insert into Pedido values (20,5,2,5)
Insert into Pedido values (21,10,2,9)
Insert into Pedido values (22,11,2,10)
Insert into Pedido values (23,12,2,4)

Insert into TipoPago values (1,0,1,0)
Insert into TipoPago values (2,0,0,1)
Insert into TipoPago values (3,0,0,1)
Insert into TipoPago values (4,1,0,0)
Insert into TipoPago values (5,0,1,0)
Insert into TipoPago values (6,0,1,0)
Insert into TipoPago values (7,1,0,0)

Insert into Pago_Metodo values (1,1)
Insert into Pago_Metodo values (2,2)
Insert into Pago_Metodo values (3,1)
Insert into Pago_Metodo values (4,4)
Insert into Pago_Metodo values (5,6)
Insert into Pago_Metodo values (6,1)
Insert into Pago_Metodo values (7,7)
Insert into Pago_Metodo values (8,1)
Insert into Pago_Metodo values (9,3)
Insert into Pago_Metodo values (10,1)
Insert into Pago_Metodo values (11,3)
Insert into Pago_Metodo values (12,3)
Insert into Pago_Metodo values (13,6)
Insert into Pago_Metodo values (14,1)
Insert into Pago_Metodo values (15,1)
Insert into Pago_Metodo values (16,3)
Insert into Pago_Metodo values (17,1)
Insert into Pago_Metodo values (18,3)
Insert into Pago_Metodo values (19,5)
Insert into Pago_Metodo values (20,5)
Insert into Pago_Metodo values (21,6)
Insert into Pago_Metodo values (22,1)