Create view vista_1 as
SELECT 
*
FROM 
  DBO.BEBIDA           BEBI
,  DBO.CLIENTE          CLIEN
,  DBO.INFO_GRAL        INFOGR
,  DBO.PAGO_METODO      METPAG
,  DBO.PEDIDO           PED
,  DBO.PLATILLO         PLAT
,  DBO.POSTRE           POST
,  DBO.RESERVACION      RESER
,  DBO.TICKET           TICKET
,  DBO.TIPOPAGO         TIPPAG
;

Create view vista_2 as
SELECT
   MAX(POSTRE_CODE)     AS CODIGO_DE_POSTRE
,  DESCRIPCION          AS DESCRIPCION_DE_POSTRE
FROM
   DBO.POSTRE
GROUP BY
   DESCRIPCION
;

Create view vista_3 as
SELECT
   SUM(TPAGO)           AS TIPO_DE_PAGO
FROM
   DBO.PAGO_METODO
;

CREATE VIEW vista_4 as
SELECT 
   COUNT(BEBIDA_CODE)     AS CODIGO_DE_BEBIDA
,  DESCRIPCION            AS DESCRIPCION_DE_BEBIDA
FROM 
   DBO.BEBIDA
GROUP BY 
   DESCRIPCION
;

Create view vista_5 as
SELECT 
   APPATERNO_C     AS APELLIDO_PATERNO
,  NOMBRE_C        AS NOMBRE_O_NOMBRES
,  APMATERNO_C     AS APELLIDO_MATERNO
FROM 
   DBO.CLIENTE
;

create view vista_6 as 
SELECT
   DESCRIPCION     AS DESCRIPTION_DE_PLATILLO
FROM
   DBO.PLATILLO
;

Create view vista_7 as
SELECT
   TPAGO_CODE      AS CODIGO_DE_TIPO_DE_PAGO
,  EFECTIVO        AS EFECTIVO
,  TDD             AS TARJETA_DE_DEBITO
,  TDC             AS TARJETA_DE_CREDITO
FROM
   DBO.TIPOPAGO
;

Create view vista_8 as
SELECT
   PEDIDO_CODE     AS CODIGO_DE_PEDIDO
,  PLATILLO_CODE   AS CODIGO_DE_PLATILLO
,  BEBIDA_CODE     AS CODIGO_DE_BEBIDA
,  POSTRE_CODE     AS CODIGO_dE_POSTRE
FROM
   DBO.PEDIDO
;

Create view vista_9 as
SELECT 
   CLIEN.NOMBRE_C         AS NOMBRES_DEL_CLIENTE
,  CLIEN.APPATERNO_C      AS APELLIDO_PATERNO_DE_CLIENTE
,  BEBI.DESCRIPCION       AS DESCRIPCION_DE_BEBIDA
,  INFOGR.TELEFONO        AS TELEFONO_DE_INFORMACION_GENERAL
,  INFOGR.CORREO          AS CORREO_DE_INFORMACION_GENERAL
,  METPAG.TPAGO           AS TIPO_DE_METODO_DE_PAGO
,  PED.PEDIDO_CODE        AS CODIGO_DEL_PEDIDO
,  PLAT.DESCRIPCION       AS DESCRIPCION_DEL_PLATILLO
,  POST.DESCRIPCION       AS DESCRIPCION_DEL_POSTRE
,  RESER.RESERVACION_CODE AS CODIGO_DE_RESERVACION
,  TICKET.TICKET_CODE     AS CODIGO_DE_TICKET
,  TIPPAG.EFECTIVO        AS PAGO_CON_EFECTIVO
,  TIPPAG.TDD             AS PAGO_CON_TARJETA_DE_DEBITO
,  TIPPAG.TDC             AS PAGOI_CON_TARJETA_DE_CREDITO
FROM 
   DBO.BEBIDA             BEBI
,  DBO.CLIENTE            CLIEN
,  DBO.INFO_GRAL          INFOGR
,  DBO.PAGO_METODO        METPAG
,  DBO.PEDIDO             PED
,  DBO.PLATILLO           PLAT
,  DBO.POSTRE             POST
,  DBO.RESERVACION        RESER
,  DBO.TICKET             TICKET
,  DBO.TIPOPAGO           TIPPAG
;

Create view vista_10 as
SELECT 
   CLIEN.NOMBRE_C         AS NOMBRES_DEL_CLIENTE
,  CLIEN.APPATERNO_C      AS APELLIDO_PATERNO_DE_CLIENTE
,  BEBI.DESCRIPCION       AS DESCRIPCION_DE_BEBIDA
,  INFOGR.TELEFONO        AS TELEFONO_DE_INFORMACION_GENERAL
,  INFOGR.CORREO          AS CORREO_DE_INFORMACION_GENERAL
,  METPAG.TPAGO           AS TIPO_DE_METODO_DE_PAGO
,  PED.PEDIDO_CODE        AS CODIGO_DEL_PEDIDO
,  PLAT.DESCRIPCION       AS DESCRIPCION_DEL_PLATILLO
,  POST.DESCRIPCION       AS DESCRIPCION_DEL_POSTRE
,  RESER.RESERVACION_CODE AS CODIGO_DE_RESERVACION
,  TICKET.TICKET_CODE     AS CODIGO_DE_TICKET
,  TIPPAG.EFECTIVO        AS PAGO_CON_EFECTIVO
,  TIPPAG.TDD             AS PAGO_CON_TARJETA_DE_DEBITO
,  TIPPAG.TDC             AS PAGOI_CON_TARJETA_DE_CREDITO
FROM 
   DBO.BEBIDA             BEBI
,  DBO.CLIENTE            CLIEN
,  DBO.INFO_GRAL          INFOGR
,  DBO.PAGO_METODO        METPAG
,  DBO.PEDIDO             PED
,  DBO.PLATILLO           PLAT
,  DBO.POSTRE             POST
,  DBO.RESERVACION        RESER
,  DBO.TICKET             TICKET
,  DBO.TIPOPAGO           TIPPAG
INNER JOIN DBO.PAGO_METODO
ON DBO.RESERVACION.RESER.RESERVACION_CODE
;

--SUBCONSULTA
SELECT * FROM Pedido
WHERE Platillo_code IN (SELECT Platillo_code FROM Platillo WHERE Platillo_code = 4)
